name: "Deploy to Balena - Draft"

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  build:
    name: "Deploy-to-Balena-Draft"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        architecture: ["aarch64", "amd64", "armv7hf"]
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Build on Balena with ${{ matrix.architecture }} architecture
        uses: balena-io/deploy-to-balena-action@master
        with:
          balena_token: ${{ secrets.BALENA_DRAFT_API_KEY }}
          fleet: github_ci_runner_adsb/balena-ads-b-${{ matrix.architecture }}
          multi_dockerignore: true
